from odoo import api, fields, models

# Installment descriptions are generated by _generate_installment_lines, so they
# are stable enough to recognise the type of installments that carry no
# `line_type` (legacy sale order lines, CRM lead installments).
INSTALLMENT_NAME_HINTS = (
    ('down payment', 'down_payment'),
    ('maintenance', 'maintenance'),
    ('annual', 'annual'),
    ('periodic', 'periodic'),
)

INSTALLMENT_ACCOUNT_FIELDS = {
    'down_payment': 'installment_down_payment_account_id',
    'periodic': 'installment_periodic_account_id',
    'annual': 'installment_annual_account_id',
    'maintenance': 'installment_maintenance_account_id',
}


class ResCompany(models.Model):
    _inherit = "res.company"

    # Accounts used on the invoice line of each installment type. When a type has
    # no account configured the line keeps the account Odoo derives from the
    # product / fiscal position.
    installment_down_payment_account_id = fields.Many2one(
        'account.account',
        string="Down Payment Account",
        check_company=True,
        help="Account set on the invoice line of Down Payment installments.",
    )
    installment_periodic_account_id = fields.Many2one(
        'account.account',
        string="Periodic Installment Account",
        check_company=True,
        help="Account set on the invoice line of periodic installments.",
    )
    installment_annual_account_id = fields.Many2one(
        'account.account',
        string="Annual Installment Account",
        check_company=True,
        help="Account set on the invoice line of annual installments.",
    )
    installment_maintenance_account_id = fields.Many2one(
        'account.account',
        string="Maintenance Account",
        check_company=True,
        help="Account set on the invoice line of maintenance installments.",
    )

    @api.model
    def _resolve_installment_type(self, line_type=False, name=False):
        """The installment type of a line, falling back to its description.

        `name` is only used for installments that carry no `line_type` (legacy
        sale order lines, CRM lead installments). Returns False when neither the
        type nor the description identifies one of the known types.
        """
        if line_type in INSTALLMENT_ACCOUNT_FIELDS:
            return line_type
        if name:
            lowered = name.lower()
            for hint, hinted_type in INSTALLMENT_NAME_HINTS:
                if hint in lowered:
                    return hinted_type
        return False

    def _get_installment_account(self, line_type=False, name=False):
        """Configured account for an installment type, or an empty recordset."""
        self.ensure_one()
        field_name = INSTALLMENT_ACCOUNT_FIELDS.get(
            self._resolve_installment_type(line_type, name)
        )
        if not field_name:
            return self.env['account.account']
        return self[field_name]
